### ISSUE TITLE
Table schema on the website

### ISSUE THREAD

**Issue by niconoe** [enram/vpts-dp#18]
Make sure all important information from the table schema (JSON file), such as min/max values, type, format, ... clearly appear in a human-readable form on the website table.

**Comment by niconoe** [comment]
Sorry @peterdesmet, I implemented a first version of this since I didn't notice you were assigned. There's probably room for improvement, though.

**Comment by peterdesmet** [comment]
The `enum` constraint was already listed under the definition, so if that one was presented, it would be listed twice. Adding a column also pushes the table to the limits on smaller screens:

<img width="540" alt="Screenshot 2021-07-05 at 13 53 05" src="https://user-images.githubusercontent.com/600993/124467642-6d182b00-dd98-11eb-8993-96d642633be8.png">

In cf35157 I updated this so that all constraints are listed under the definition: enum first (as a value list, see example: https://tdwg.github.io/camtrap-dp/data/#bait_use), then the other constraints (as a key: value list). This also frees up some horizontal space:

<img width="542" alt="Screenshot 2021-07-05 at 13 53 32" src="https://user-images.githubusercontent.com/600993/124467771-95078e80-dd98-11eb-9f09-4b890ab4927e.png">
