### ISSUE TITLE
Should datasets link to specs or include specs?

### ISSUE THREAD

**Issue by peterdesmet** [enram/vpts-dp#24]
Should a VPTS dataset link to the [specifications for its csv files](https://github.com/enram/vpts-dp/blob/main/vpts-table-schema.json) (i.e. the table schema):

```json
"resources": [
    {
      "name": "vpts",
      "path": ["vpts1.csv", "vpts2.csv"],
      "profile": "tabular-data-resource",
      "schema": "https://raw.githubusercontent.com/enram/vpts-dp/0.1/vpts-table-schema.json"
    }
]
```

Or include those verbosely?

```json
"resources": [
    {
      "name": "vpts",
      "path": ["vpts1.csv", "vpts2.csv"],
      "profile": "tabular-data-resource",
      "schema": {
        "fields": [
          {
            "name": "datetime",
            "description": "Event date and time as an ISO8601 format string, UTC time",
            "type": "datetime",
            "format": "YYYY-MM-DDThh:mm:ssZ",
            "example": "2019-03-27T10:55:00Z",
            "constraints": {
              "required": true
            }
          },
          ...
        ]
      }
    }
]
```

1. The main _advantage_ of linking is that you **know exactly which version of the schema** you are validating against. If the producer included it verbosely, he/she can deviate from the schema (e.g. removing all requirements, which makes validation moot), which makes it a lot harder to **compare datasets** too.
2. The main _disadvantage_ in linking is that that you **need to include all fields of the schema** in the csv files, even when not used. The fields should also be in the **same order**. This is mainly annoying for users (a bunch of empty columns), but not for machines (which can much easier compare and combine across datasets).

For Camtrap DP we opted for linking. @niconoe @adokter @CeciliaNilsson709 @bart1 any preferences?

**Comment by peterdesmet** [comment]
If we adopt linking, then the note on this page https://enram.github.io/vpts-dp/data/

> To make data exploration (by humans!) more comfortable, it is considered good practice (but not mandatory) that the fields are presented in the same order as in the table below.

Becomes a requirement + datasets have to include all the fields.

**Comment by niconoe** [comment]
I think I prefer the linking solution, the advantages seems more important than the disadvantages. 

I think a good approach in general is to make things as clear and defined as possible so the standard does not encourage any deviation. That might look rigid to users, but IMHO it's better to convince them to use it by also providing a great ecosystem than by being too lose about the specifications (which would slower the ecosystem development, and subsequently slow down adoption).

There are different but related things that are not 100% clear to me:

- With frictionless, can't we "just" provide a global profile.json that not only describes the metadata, but also links the specific table profile that the data file should comply with? (in other words, do we have to say to users to refer to two specs file, or can a single one reference the other)? That would appear more clear to me?
- I cant't find the information in frictionless specs: should the fields be indeed in the same order than in the profile.json? What happens if an embedded CSV file provide headers with the same fields than in the JSON file, but in a different order?

**Comment by peterdesmet** [comment]
👍 

To answer your questions, these are 2 shortcomings of Frictionless:

1. Yes, I believe you need to link to both files, but should investigate this more
2. Yes, they need to be in same order and same amount. There is a parameter in Frictionless Software to map on header name (`--sync-schema`) but that is not the default, so it is better not to implement it as such.

**Comment by peterdesmet** [comment]
We opted for a simple flat format as described in #25, so the question to include or reference specs becomes moot (you can do neither in a csv file, except maybe as `# comment lines`). However, a tool like vptstools can easily use frictionless tools to validate a source file against the specs defined in this repository. See #14.
