### ISSUE TITLE
Do we allow C and S string values for radar_wavelength

### ISSUE THREAD

**Issue by peterdesmet** [enram/vpts-dp#30]
See http://adriaandokter.com/bioRad/reference/read_vpts.html?q=wave#arguments:

> Radar wavelength in cm, or one of 'C' or 'S' for C-band and S-band radar, respectively, in which case C-band wavelength is assumed to be 5.3 cm and S-band wavelength 10.6 cm

My 2 cents: we should not allow `C` and `S` values in the `radar_wavelength` column, only numeric values.

**Comment by adokter** [comment]
The string version was added because sometimes the wavelength meta-data was missing or unknown, while people do tend to know the band. In that case,  5.3 vs 10.6 are decent best guesses for C- and S-band (which is considerably better than 5 cm vs 10 cm, which people might use when they have no wavelength information besides the band). But I'm open to a different solution, as long as we keep suggesting a best guess for C- and S-band if the user doesn't know the wavelength

**Comment by peterdesmet** [comment]
I have updated the definition to:

> Wavelength of the radar in cm. If unknown, use 5.3 cm for C-band radar and 10.6 cm for S-band radar.

I would then not allow the values `C` and `S`.
