### ISSUE TITLE
Exclude empty string as missing values in table specification?

### ISSUE THREAD

**Issue by stijnvanhoey** [enram/vpts-dp#37]
@peterdesmet, see https://github.com/enram/vpts-csv/blob/main/vpts-csv-table-schema.json#L259, whereas this is [not mentioned in the specs](https://aloftdata.eu/vpts-csv/#requirements)

**Comment by peterdesmet** [comment]
@adokter preferred to express missing values as `NA` in the CSV files, see https://github.com/enram/vpts-csv/issues/23#issuecomment-1123960877.  I personally prefer empty values because it is more of a default and makes data files smaller. @adokter do you stick with your preference?

Note: if we stick with the current recommendation, I think that (existing) files that have coded it as empty strings should not fail validation. So I would therefore allow both, but recommend (therefore `SHOULD` not `MUST`) to use `NA` when producing VPTS CSV.

**Comment by adokter** [comment]
I stick with my preference but don't feel extremely strongly, as long as nodata and undetect values remain distinguishable, and get mapped in bioRad objects to the old NA/NaN values, keeping the convention we had

**Comment by peterdesmet** [comment]
In that case I prefer to express nodata as empty values in CSV, as that sticks closer to conventions and is less verbose.

@adokter in R (default behaviour) both empty values and NA values are interpreted as NA (and "NaN" as NaN), so there is no issue there.

Using this [test.csv](https://github.com/enram/vpts-csv/files/10032257/test.csv):

```R
# with read.csv
> read.csv("test.csv")
#              type value
# 1        undetect   NaN
# 2    nodata_as_NA    NA
# 3 nodata_as_empty    NA

# with readr
readr::read_csv("test.csv")
# A tibble: 3 × 2
#   type            value
#   <chr>           <dbl>
# 1 undetect          NaN
# 2 nodata_as_NA       NA
# 3 nodata_as_empty    NA
```

@stijnvanhoey I would then suggest to update the specs:

- nodata values SHOULD be expressed as empty values.
- But still leave "NA" in `missingValues` as a valid way to express those.

**Comment by peterdesmet** [comment]
Updated in the standard:

https://github.com/enram/aloftdata.eu/blob/b3745dba08f7a17e3fa94ac5358a2f1bd2e1ee80/pages/vpts-csv.md?plain=1#L31-L34

`missingValues` remains the same (so `NA` as empty value is allowed, but not mentioned under `SHOULD`):

https://github.com/enram/vpts-csv/blob/1272c02df3913dfcd5138acd772dac8a1b194ff1/vpts-csv-table-schema.json#L258-L261
